# Funding options for BlazeCSV
# Uncomment and configure as needed

# github: yourusername
# patreon: yourusername
# open_collective: blazecsv
# ko_fi: yourusername
# custom: ["https://your-custom-link.com"]
