name: Feature Request
description: Suggest a new feature for BlazeCSV
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Performance optimization
        - New parsing feature
        - Error handling
        - API enhancement
        - Documentation
        - Platform support
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you'd like to use this feature.
      placeholder: |
        ```cpp
        #include <blazecsv/blazecsv.hpp>

        // How you'd like to use the new feature
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or benchmarks about the feature request here.
